version: "2"

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - govet
    - gocritic
    - unused
    - ineffassign
    - bodyclose
    - nilerr
    - errcheck
    - staticcheck
    - gosimple

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - bodyclose
          - errcheck
