version: 2

project_name: bb

builds:
  - main: .
    binary: bb
    ldflags:
      - -s -w
      - -X github.com/tyrantkhan/bb/cmd.Version={{.Version}}
      - -X github.com/tyrantkhan/bb/cmd.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

homebrew_casks:
  - name: bb
    binaries:
      - bb
    directory: Casks
    repository:
      owner: tyrantkhan
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    url:
      template: "https://github.com/tyrantkhan/bitbucket-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/tyrantkhan/bitbucket-cli/"
    homepage: "https://github.com/tyrantkhan/bitbucket-cli"
    description: "Bitbucket Cloud CLI"
